### ISSUE TITLE
Add fathom analytics to pin library

### ISSUE THREAD

**Issue by dthiex** [sentinel-hub/pin-library#11]
We would like to see how many people are using the pin library. 

To record this, we use fathom analytics (in our other apps). Please add this to the code `<script src="https://water-knowing.sentinel-hub.com/script.js" data-site="SMIPSXOZ" defer></script>`

As fathom it's not collecting any personal data or setting cookies there is no need for one of those annoying pop-ups.

**Comment by Developer1510** [comment]
Added here: https://github.com/sentinel-hub/pin-library/pull/14
